apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sendmail
  namespace: default
spec:
  type: bindings.azure.servicebusqueues
  metadata:
  - name: connectionString
    value: "Endpoint=sb://edwinvw01.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XCkcm24+TvV80VYdtejDsIYPQJQnhbVm+hGF5xuiALY="
  - name: queueName
    value: pulse
  - name: ttlInSeconds
    value: 3600